/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedInsightsRouteImport } from './routes/_authenticated/insights'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedProblemsRouteImport } from './routes/_authenticated/problems'
import { Route as AuthenticatedProblemsIdRouteImport } from './routes/_authenticated/problems_.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInsightsRoute = AuthenticatedInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProblemsRoute = AuthenticatedProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProblemsIdRoute = AuthenticatedProblemsIdRouteImport.update({
  id: '/problems_/$id',
  path: '/problems/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notebook': typeof NotebookRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/new': typeof AuthenticatedNewRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/problems/$id': typeof AuthenticatedProblemsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/notebook': typeof NotebookRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/insights': typeof AuthenticatedInsightsRoute
  '/new': typeof AuthenticatedNewRoute
  '/problems': typeof AuthenticatedProblemsRoute
  '/problems/$id': typeof AuthenticatedProblemsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/notebook': typeof NotebookRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/insights': typeof AuthenticatedInsightsRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/problems': typeof AuthenticatedProblemsRoute
  '/_authenticated/problems_/$id': typeof AuthenticatedProblemsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/notebook'
    | '/dashboard'
    | '/insights'
    | '/new'
    | '/problems'
    | '/problems/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/notebook'
    | '/dashboard'
    | '/insights'
    | '/new'
    | '/problems'
    | '/problems/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/notebook'
    | '/_authenticated/dashboard'
    | '/_authenticated/insights'
    | '/_authenticated/new'
    | '/_authenticated/problems'
    | '/_authenticated/problems_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  NotebookRoute: typeof NotebookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/insights': {
      id: '/_authenticated/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthenticatedInsightsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems': {
      id: '/_authenticated/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof AuthenticatedProblemsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/problems_/$id': {
      id: '/_authenticated/problems_/$id'
      path: '/problems/$id'
      fullPath: '/problems/$id'
      preLoaderRoute: typeof AuthenticatedProblemsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInsightsRoute: typeof AuthenticatedInsightsRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedProblemsRoute: typeof AuthenticatedProblemsRoute
  AuthenticatedProblemsIdRoute: typeof AuthenticatedProblemsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInsightsRoute: AuthenticatedInsightsRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedProblemsRoute: AuthenticatedProblemsRoute,
  AuthenticatedProblemsIdRoute: AuthenticatedProblemsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  NotebookRoute: NotebookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
